org.gradle.jvmargs=-Xmx1200m -XX:MaxMetaspaceSize=384m
org.gradle.parallel=false

# Fabric Loom / Minecraft
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3

# Mod
mod_version=1.0.0
maven_group=com.lovely.autodrop
archives_base_name=lovelyautodrop

# Dependencies
fabric_version=0.141.5+1.21.11
fabric_kotlin_version=1.13.13+kotlin.2.4.10
kotlin_version=2.4.10
org.gradle.daemon=false
org.gradle.configuration-cache=false
